DROP TABLE IF EXISTS buddy_table; 
CREATE TABLE buddy_table (ProductName VARCHAR(255), ProductPage VARCHAR(255), ProductDescription VARCHAR(255), OriginalPrice VARCHAR(255), DiscountedPrice VARCHAR(255), DiscountRate VARCHAR(255), ImageLink VARCHAR(255));

INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('222 Banda Annistonel Track Jacket - Black', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-annistonel-track-jacket-black', '222 Mens leather trackjacket. REGULAR FIT. Rib borders, full zip in front, two front pockets. Omini Logo tape embossed and piping, applied on sleeves. Embroidery Omini Logo. Textile Composition: Leather 100%', '$350.00', '$297.50', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('222 Banda Rastoriazzel Trackpants - Black', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-rastoriazzel-trackpants-black', '222 Mens Leather trackpants with bottom border in rib. REGULAR FIT. Omini Logo tape embossed and piping. Waist band with elastic inside and drawcord, two side pockets, one back zipped pocket. Embroidery Omini Logo. Textile Composition: Leather 100%', '$300.00', '$255.00', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('222 Banda Bucket Hat - Black', 'https://kappa-usa.com/collections/mens-sale/products/kappa-ss22-222-banda-buckete-bucket-hat-black', '222 Leather bucket hat. Banda con ripetizione Logo Omini embossed and embroidery Omini Logo. Textile Composition:  Leather 100%', '$180.00', '$153.00', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('222 Banda Annistonel Track Jacket - Red', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-annistonel-track-jacket-red', '222 Mens leather trackjacket. REGULAR FIT. Rib borders, full zip in front, two front pockets. Omini Logo tape embossed and piping, applied on sleeves. Embroidery Omini Logo. Textile Composition: Leather 100%', '$350.00', '$297.50', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('222 Banda Bucket Hat - Red', 'https://kappa-usa.com/collections/mens-sale/products/kappa-ss22-222-banda-buckete-bucket-hat-red', '222 Leather bucket hat. Banda con ripetizione Logo Omini embossed and embroidery Omini Logo. Textile Composition: Leather 100%', '$180.00', '$153.00', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Rakes Cap - Red', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-race-rakes-cap-red', 'Unisex cap in cotton twill. Flat visor, plastic regulation. Embroidered patches. Textile Composition: Cotton 100%', '$50.00', '$42.50', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Rakes Cap - Black Smoke', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-race-rakes-cap-black-smoke', 'Unisex cap in cotton twill. Flat visor, plastic regulation. Embroidered patches. Textile Composition: Cotton 100%', '$50.00', '$42.50', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Meppel Cap - Green Olive', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-meppel-cap-green-olive', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Anfrei Cap - Green Olive', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-anfrei-cap-green-olive', 'AUTHENTIC Unisex cap. Adjustable strap at back. Kappa lettering and Omini logo.', '$40.00', '$34.00', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Hoogeveen Cap - Green Olive', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-hoogeveen-cap-green-olive', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Hoogeveen Cap - Beige', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-hoogeveen-cap-beige', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Hoogeveen Cap - Black Smoke Orange', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-hoogeveen-cap-black-smoke-orange', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('Authentic Phuket Bucket Hat - Olive Green Pink', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-phuket-bucket-hat-olive-green-pink', 'AUTHENTIC. Unisex bucket hat in cotton twill. Authentic logo, all over print. Textile Composition: Cotton 100%', '$55.00', '$46.75', '18%');
INSERT INTO buddy_table (ProductName, ProductDescription, ProductPage, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink)VALUES ('222 Banda Aderno 2 Trackpants - Black Smoke', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-aderno-2-trackpants-black-smoke', 'Mens sport trousers in brushed tricot. SLIM FIT. Elasticated waistband, side pockets with zipper, zipper on bottom legs. Laser-cut Omini logo. Textile Composition: Polyester 100%', '$80.00', '$64.00', '25%');
