CREATE TABLE clothing_info (
 ProductName VARCHAR(255) PRIMARY KEY,
 ProductCategory VARCHAR(255),
 ProductPage VARCHAR(255),
 ProductDescription VARCHAR(1000),
 OriginalPrice VARCHAR(10),
 DiscountedPrice VARCHAR(10),
 DiscountRate VARCHAR(10),
 ImageLink VARCHAR(255)
);

INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('222 Banda Annistonel Track Jacket - Black', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-annistonel-track-jacket-black', '222 Mens leather trackjacket. REGULAR FIT. Rib borders, full zip in front, two front pockets. Omini Logo tape embossed and piping, applied on sleeves. Embroidery Omini Logo. Textile Composition: Leather 100%', '$350.00', '$297.50', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/leatherjktblk-1_180x.jpg?v=1645741611');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('222 Banda Rastoriazzel Trackpants - Black', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-rastoriazzel-trackpants-black', '222 Mens Leather trackpants with bottom border in rib. REGULAR FIT. Omini Logo tape embossed and piping. Waist band with elastic inside and drawcord, two side pockets, one back zipped pocket. Embroidery Omini Logo. Textile Composition: Leather 100%', '$300.00', '$255.00', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/leatherpantblk-1_180x.jpg?v=1645741678');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('222 Banda Bucket Hat - Black', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-ss22-222-banda-buckete-bucket-hat-black', '222 Leather bucket hat. Banda con ripetizione Logo Omini embossed and embroidery Omini Logo. Textile Composition:  Leather 100%', '$180.00', '$153.00', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/BUCKETHAT-BLK-1_180x.jpg?v=1645746695');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('222 Banda Annistonel Track Jacket - Red', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-annistonel-track-jacket-red', '222 Mens leather trackjacket. REGULAR FIT. Rib borders, full zip in front, two front pockets. Omini Logo tape embossed and piping, applied on sleeves. Embroidery Omini Logo. Textile Composition: Leather 100%', '$350.00', '$297.50', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/leatherjktred-1_180x.jpg?v=1645741737');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('222 Banda Bucket Hat - Red', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-ss22-222-banda-buckete-bucket-hat-red', '222 Leather bucket hat. Banda con ripetizione Logo Omini embossed and embroidery Omini Logo. Textile Composition: Leather 100%', '$180.00', '$153.00', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/BUCKETHAT-RED-1_180x.jpg?v=1645746701');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Rakes Cap - Red', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-race-rakes-cap-red', 'Unisex cap in cotton twill. Flat visor, plastic regulation. Embroidered patches. Textile Composition: Cotton 100%', '$50.00', '$42.50', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/341B83W-00E-1_180x.jpg?v=1646240590');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Rakes Cap - Black Smoke', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-race-rakes-cap-black-smoke', 'Unisex cap in cotton twill. Flat visor, plastic regulation. Embroidered patches. Textile Composition: Cotton 100%', '$50.00', '$42.50', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/341B83W-088-1_180x.jpg?v=1645208314');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Meppel Cap - Green Olive', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-meppel-cap-green-olive', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/311H1WW-C05-1_180x.jpg?v=1646326073');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Anfrei Cap - Green Olive', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-anfrei-cap-green-olive', 'AUTHENTIC Unisex cap. Adjustable strap at back. Kappa lettering and Omini logo.', '$40.00', '$34.00', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/361B4KW-A0D-1_180x.jpg?v=1646240772');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Hoogeveen Cap - Green Olive', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-hoogeveen-cap-green-olive', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/34171NW-C05-1_180x.jpg?v=1646326123');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Hoogeveen Cap - Beige', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-hoogeveen-cap-beige', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/34171NW-C06-1_180x.jpg?v=1646240854');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Hoogeveen Cap - Black Smoke Orange', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-hoogeveen-cap-black-smoke-orange', 'AUTHENTIC. Cap unisex in di cotton twill. Branded metal buckle regulation. Embroidered Kappa lettering and Omini logo. Textile Composition: Cotton 100%', '$35.00', '$29.75', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/34171NW-C01-1_180x.jpg?v=1646326107');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Authentic Phuket Bucket Hat - Olive Green Pink', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-authentic-phuket-bucket-hat-olive-green-pink', 'AUTHENTIC. Unisex bucket hat in cotton twill. Authentic logo, all over print. Textile Composition: Cotton 100%', '$55.00', '$46.75', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/381C4PW-NA1-1_180x.jpg?v=1644970915');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('222 Banda Aderno 2 Trackpants - Black Smoke', 'mens', 'https://kappa-usa.com/collections/mens-sale/products/kappa-mens-ss22-222-banda-aderno-2-trackpants-black-smoke', 'Mens sport trousers in brushed tricot. SLIM FIT. Elasticated waistband, side pockets with zipper, zipper on bottom legs. Laser-cut Omini logo. Textile Composition: Polyester 100%', '$80.00', '$64.00', '25%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/33192TW-A00-1_180x.jpg?v=1643665734');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Ceci Hoodie - Purple', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-ceci-hoodie-purple', 'Womens french terry cropped hoodie REGULAR FIT.  graphics on left and right sleeves Textile Composition: Cotton 80% - Polyester 20%', '$80.00', '$56.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/381F5HW-A01-1_180x.jpg?v=1659045472');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Tape Eva Leggings - Black Smoke', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-tape-eva-leggings-black-smoke', 'Womens leggings in heavy jersey fabric. SKIN FIT. Elasticated waist. Logo Tape applied on the side. Omini Logo and HD printed on front. Textile Composition: Elastane 12% - Polyester 88%', '$80.00', '$56.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/311E5MW-A11-1_180x.jpg?v=1660681070');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Tape Eva Leggings - Purple', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-tape-eva-leggings-purple', 'Womens leggings in heavy jersey fabric. SKIN FIT. Elasticated waist. Logo Tape applied on the side. Omini Logo and HD printed on front. Textile Composition: Elastane 12% - Polyester 88%', '$80.00', '$56.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/311E5MW-A13-1_180x.jpg?v=1659045387');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Tape Enami Track Jacket - Purple', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-tape-enami-track-jacket-purple', 'Womens French Terry half zip jacket. REGULAR FIT. Long sleeves, half zip, drawstring at the bottom. Logo Tape application on the zip. Logo embroidered on the chest. Textile Composition: Cotton 80% - Polyester 20%', '$110.00', '$77.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/311N1UW-A13-1_180x.jpg?v=1659045418');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Tape Enami Track Jacket - Black Smoke', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-tape-enami-track-jacket-black-smoke', 'Womens French Terry half zip jacket. REGULAR FIT. Long sleeves, half zip, drawstring at the bottom. Logo Tape application on the zip. Logo embroidered on the chest. Textile Composition: Cotton 80% - Polyester 20%', '$110.00', '$77.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/311N1UW-A11-1_180x.jpg?v=1659482544');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Tape Edda Sweatpants - Black Smoke', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-tape-edda-leggings-black-smoke', 'Womens sweatpants in French Terry fabric. SLIM FIT. Ribbed bottom and elasticated waist. Logo Tape applied on the side. Omini Logo embroidered on leg. Textile Composition: Cotton 80% - Polyester 20%', '$90.00', '$63.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/381E75W-A11-1_180x.jpg?v=1659045443');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Ceci Hoodie - Pink', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-ceci-hoodie-pink', 'Womens french terry cropped hoodie REGULAR FIT. graphics on left and right sleeves Textile Composition: Cotton 80% - Polyester 20%', '$80.00', '$56.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/381F5HW-A05-1_180x.jpg?v=1658944226');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Tape Eva Leggings - Pink', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-tape-eva-leggings-pink', 'Womens leggings in heavy jersey fabric. SKIN FIT. Elasticated waist. Logo Tape applied on the side. Omini Logo and HD printed on front. Textile Composition: Elastane 12% - Polyester 88%', '$80.00', '$56.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/311E5MW-A12-4_180x.jpg?v=1658786163');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Logo Tape Edda Sweatpants - Pink', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-fw22-logo-tape-edda-sweatpants-pink', 'Womens sweatpants in French Terry fabric. SLIM FIT. Ribbed bottom and elasticated waist. Logo Tape applied on the side. Omini Logo embroidered on leg. Textile Composition: Cotton 80% - Polyester 20%', '$90.00', '$63.00', '43%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/381E75W-A12-1_180x.jpg?v=1658785375');
INSERT INTO clothing_info (ProductName, ProductCategory, ProductPage, ProductDescription, OriginalPrice, DiscountedPrice, DiscountRate, ImageLink) VALUES ('Koral x Kappa Lustrous High Rise Infinity Leggings', 'womens', 'https://kappa-usa.com/collections/womens-sale/products/kappa-womens-koral-lustrous-high-rise-infinity-leggings', 'Add the perfect pop of color to your workout wardrobe in these exclusive street-sport graffiti print. Mix and match or pair it perfectly with our Stadium Infinity Sports Bra.¬¨‚Ä†KORAL X KAPPA have teamed up for a contemporary fashion capsule collection that reinterprets classic silhouettes for the modern woman. Launching in Summer 2020 the collection features street-art inspired prints in bold colors using premium activewear fabrics sourced from around the world.¬¨‚Ä†High rise. Perfect ankle length. Waistband pocket for storage on the go. High performance leggings in our signature Infinity fabric.', '$96.00', '$81.60', '18%', 'https://cdn.shopify.com/s/files/1/2447/5525/products/leggings-1_180x.jpg?v=1584380699');
